require 'yaml'

git = YAML::load_file(File.join(__dir__, '.git-branch.yaml'))


Vagrant.configure('2') do |config|


  config.vm.define "centos42f"  do |centos42f|
		centos42f.vm.provider "virtualbox" do |v|
			v.memory = 4500
			v.cpus = 2
		end
		
		#centos42f.vm.network "public_network"
    centos42f.vm.network "forwarded_port", guest: 8443, host: 18443


		centos42f.vm.box = "puppetlabs/centos-7.2-64-puppet"
    centos42f.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; \
        if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; \
          then apt-get update; \
        else \
					yum clean all
					yum install -y deltarpm
          yum -y update; \
        fi; \
        /vagrant/bootstrap.sh; \
        /vagrant/start.sh centos42f " + git['branch']
    end
		centos42f.vm.provision :shell, path: "tests.sh"
  end

  config.vm.define "centos50x"  do |centos50x|
		centos50x.vm.provider "virtualbox" do |v|
			v.memory = 4500
			v.cpus = 2
		end
		
		#centos50x.vm.network "public_network"
    centos50x.vm.network "forwarded_port", guest: 8443, host: 18444

		centos50x.vm.box = "puppetlabs/centos-7.2-64-puppet"
    centos50x.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; \
        if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; \
          then apt-get update; \
        else \
          yum -y update; \
        fi; \
        /vagrant/bootstrap.sh; \
        /vagrant/start.sh centos50x " + git['branch']
    end
		centos50x.vm.provision :shell, path: "tests.sh"
  end

  config.vm.define "ubuntu42f" do |ubuntu42f|
		ubuntu42f.vm.provider "virtualbox" do |v|
			v.memory = 4500
			v.cpus = 2
		end
		
	#	ubuntu42f.vm.network "public_network"
    ubuntu42f.vm.network "forwarded_port", guest: 8443, host: 18445

		ubuntu42f.vm.box = "ubuntu/trusty64"
    ubuntu42f.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; \
        if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; \
          then apt-get update; \
        else \
          yum -y update; \
        fi; \
        /vagrant/bootstrap.sh; \
        /vagrant/start.sh ubuntu42f " + git['branch']
    end
		ubuntu42f.vm.provision :shell, path: "tests.sh"
  end

  config.vm.define "ubuntu50x" do |ubuntu50x|
		ubuntu50x.vm.provider "virtualbox" do |v|
			v.memory = 4500
			v.cpus = 2
		end
		
		
    #ubuntu50x.vm.network "public_network"
    ubuntu50x.vm.network "forwarded_port", guest: 8443, host: 18446

		ubuntu50x.vm.box = "ubuntu/trusty64"
    ubuntu50x.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; \
        if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; \
          then apt-get update; \
        else \
          yum -y update; \
        fi; \
        /vagrant/bootstrap.sh; \
        /vagrant/start.sh ubuntu50x " + git['branch']
    end
		ubuntu50x.vm.provision :shell, path: "tests.sh"
  end


end
